### ISSUE TITLE
Confirmed now, q4_0 is (still) broken

### ISSUE THREAD

**Issue by GameOverFlowChart** [Vali-98/ChatterUI#209]
So I finally had the chance to make the comparison. Since the update to q4_0 which should make them more performant, they became unuseful slow. I made a comparison with q4ks.
8B q4_0 4.67GB: freezes not just the app but the whole phone.
8B q4_K_S 4.68GB: runs like always. Notice that it's even minimal bigger in file size. 
Reminder: I was able to run Q4_0_4_4 in the past and with this version q4_0 should behave like Q4_0_4_4.

I also made sure that the problem is not related to having the weights in internal storage or external. The behavior is the same in both cases. 

I made the test with version 0.8.4a.
If the problem is in llamacpp and not chatterui, we should probably tell them about the problem.

**Comment by Vali-98** [comment]
Thanks for this update, there actually was a recent bug found in llama.rn on some fp16 compilation flags causing issues,

I uploaded a [v0.8.5 beta](https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.5-beta1) with an updated llama.cpp / build process. Let me know if this works.

**Comment by GameOverFlowChart** [comment]
> Thanks for this update, there actually was a recent bug found in llama.rn on some fp16 compilation flags causing issues,
> 
> I uploaded a [v0.8.5 beta](https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.5-beta1) with an updated llama.cpp / build process. Let me know if this works.

Still the same, no problem with q4ks, but q4_0 slows down the device (the phone kills my dynamic wallpaper, I guess to free some resources also the Android buttons respond late so it's not easy to leave the app).  But the loading bar filled fast this time, at first I thought the problem was solved.

**Comment by Vali-98** [comment]
I'm assuming something is going very wrong with the model repacking, or for whatever reason memory is not being released properly.

What hardware was this tested on? Does your device allow for 'memory extension' using the device storage? If so, is it enabled?

**Comment by GameOverFlowChart** [comment]
> I'm assuming something is going very wrong with the model repacking, or for whatever reason memory is not being released properly.
> 
> What hardware was this tested on? Does your device allow for 'memory extension' using the device storage? If so, is it enabled?

12gb ram, Snapdragon 888, Android 14, memory extension is disabled and I wouldn't activate it ever.

**Comment by GameOverFlowChart** [comment]
Does chatterui or llamacpp do the detection of supported cpu instructions? What if the model gets repacked as Q4_0_4_8 instead of Q4_0_4_4?
The old version of chatterui was able to correctly show which one was supported by my device. According to my memory despite being slow I had the model outputing a response as I first encountered this problem. I don't know if that would be possible with wrong repacking or if it would just be as inefficient as it is.

**Comment by Vali-98** [comment]
llama.rn manages the cpu flag selection by checking flags provided by the OS. For i8mm, it simply checks for the `i8mm` flag.

If you have `logcat`, you can filter `rnllama` to check the startup routine, it should list your device capabilities:

![Image](https://github.com/user-attachments/assets/9112dde6-8d81-4dff-b6b0-c9005bf1cc15)

You can get said platform-tools here: https://developer.android.com/tools/releases/platform-tools

**Comment by Vali-98** [comment]
> I think that's because of llamacpp. They cease to support that quant from an update. I can't remember exactly, but you can search there.

This issue is more about Q4_0 vs the now outdated Q4_0_4_8 quants. For some reason, performance of Q4_0 is worse.

**Comment by Vali-98** [comment]
Checking in, has this been solved by latest llama.cpp + `largeHeap`?
https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.6-beta6

**Comment by GameOverFlowChart** [comment]
> Checking in, has this been solved by latest llama.cpp + `largeHeap`? https://github.com/Vali-98/ChatterUI/releases/tag/v0.8.6-beta6

Hey I'm going to try it out later, I let you know.

**Comment by Vali-98** [comment]
Let me know if this has been fixed on latest (not the debug version).

Also, have you tested with 4_0 quants instead of Q4KS? I do not believe 4KS benefits from repacking.

**Comment by GameOverFlowChart** [comment]
> Let me know if this has been fixed on latest (not the debug version).
> 
> Also, have you tested with 4_0 quants instead of Q4KS? I do not believe 4KS benefits from repacking.

v0.8.6 still broken. And yes of course, as I already reported, 4_0 is broken because of the repacking and Q4KS works fine.

**Comment by Vali-98** [comment]
As much as I want to say I can fix this, after a lot of testing it seems like this is caused by small memory spike during the repacking process and my efforts to rewriting the model loader have been unfruitful. That said, this is only an issue if you teeter close to your memory limit, eg. 14b models on my device cause a crash, but 12b and under can be repacked safely.

I think I have to throw in the towel and finally say that this cannot be fixed, and the only real solution is getting better hardware.
